# vercel-merge.yml
name: Deploy to vercel on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
      - uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: fhulufhelo-tours-website
          envVariableKeys: CLIENT_EMAIL,PRIVATE_KEY,SPREADSHEET_ID
        env:
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          TARGET_CLIENT_EMAIL: preview,development,production
          TYPE_CLIENT_EMAIL: encrypted

          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          TARGET_PRIVATE_KEY: preview,development,production
          TYPE_PRIVATE_KEY: encrypted

          SPREADSHEET_ID: ${{ secrets.EVENTS_APP_SPREADSHEET_ID }}
          TARGET_SPREADSHEET_ID: preview,development,production
          TYPE_SPREADSHEET_ID: encrypted
          
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
